export interface Product {
    productId: number,
    categoryId: number,
    productName: string,
    shortDescription: string,
    friendlypagename: string,
    disableBuyButton: boolean,
    displayOrder: number,
    imageUrl: string,
    parentProductId: number,
    isFeatureProduct: true,
    productPrice: number,
    premiumDiscount: number,
    productWeight: number,
    showOnHomepage: boolean,
    colorClass: string,
    iconClass: string,
    availability: string,
    stock: number,
    isBundle: boolean,
    marketingTagId: 1,
    tagName: string,
    tagColor: string,
    metalId: number,
    tierpriceapply: boolean
}