export const ENDPOINTS = {
    getConfigStore: 'store/duMyjVf3k0KIi7Rq7CmHAA',
    getTicker: 'calculator/DMJqdS7VvR2VMk9R',
    getProduct: 'product/m9XieCcNOUOxk5ODsP6FXQ/0',
    getSlider: 'home/Y9w8nK5PhEyKFBZQNbV2Ow',
    getFooterLink: 'home/N2KdtXS5z0W3EbgvHaDCGw',
    homePageSection: 'home/sMwXo8EJm8Pad',
    getBlog: 'Blog/jk9mPhOPvkiq6luNZrwanA',
    postNewsLetter: 'home/kQTLjU9dZ0KZSxQFBegdRQ',
    postSubscribeNewsletter: 'home/kQTLjU9dZ0KZSxQFBegdRQ',
    topCategoriesListWithSubCategories: "category/xwfjo7TszkKNuYNfIbYrog",
    productPrices: 'price/deSo8Uy3q0Cz2LZ4gBy0vQ',
    login: '/login',
    loginUser: 'account/JO6SKzu1bEGLAizHldGDcg',
    ImpersonateSignIn: 'account/SdcEKDGa6sV',
    BlogList: 'Blog/jk9mPhOPvkiq6luNZrwanA',
    BlogDetails: 'Blog/71pfOKTeVEupzihE5QeGGQ',
    NewsList: 'News/yXO7kEBPR0WMiRINsNssAQ',
    NewsDetails: 'News/DoSnNVHaXUqBd12mBffQTA',
    logOutUser: 'account/VH7qPWBrFW1lA',
    forgotPasswordLink: "https://register.qmint.com/passwordrecovery",
    createMyAccount: "https://queenslandmint.com/register?returnUrl=",
    membership: "Checkout/rsBDWqaTLMJauU",
    getCategoryData: "category/nRuA1KTPi0q4Outgqr39qw",
    getContactUsConfiguration: "ContactUs/gGu8GSaHhEWKVZICJLtoeg",
    reasonsForContact: "ContactUs/zdT918BBCkKYQBI2D1D0fw",
    saveContactUsDetails: "ContactUs/jn1Gr1IOubQbzQV5S",
    saveCalculators: "calculator/WOGEEHFLeeZisCtFqHdkfpdUrLN",
    productDetails: "product/wb5rqwFBf0ua22kGp0Hlhw/{{product-id}}",
    priceForprogressbar: "price/{{product-id}}/jGnpTVO8S0aP1590ehZu3g?hZHxveDw={{timeinterval}}",
    addToCartProduct: "shoppingcart/CxdrQaZ030ekw4jdCgWWKA",
    getShoppingCartData: "shoppingcart/QcKa33GRtUanfuqzmFFM6A",
    updateShoppingCartData : "shoppingcart/OVixigTa9U6RcJbCK7pV2Q",
    clearShoppingCartData : "shoppingcart/7I7YbS9bX0asi1DVUXT60w",
    recentlyViewdProducts: 'product/dS99jwa0akmwbLKOuSs9dA',
    compareProducts : "product/v07u2ZDwV0mGrWHpPYzaKA"
}
export const StoreData = {
    storeCode: 12,
    returnUrl: typeof window !== 'undefined' ? window.location.href : null
}