let billingAddess = {
    "addressId": 101877,
    "addressType": 1,
    "customerId": 74038,
    "firstName": "test!!! by noy none xyz",
    "lastName": "user",
    "addressLine1": "Sanva Primary School,  Road,  Sanva",
    "addressLine2": "Sanva Primary School,  Road,  Sanva",
    "city": "Beerwah",
    "state": 4,
    "postcode": 4519,
    "country": 85,
    "phone1": "917228040585",
    "email": "usernewtest425@yopmail.com",
    "isSource": "10",
    "isVerified": false,
    "company": "322",
    "isactive": true,
    "storeCode": 8,
    "stateName": "Alaska",
    "countryName": "Uzbekistan"
}
let shippingAddress = {
    "addressId": 101879,
    "addressType": 2,
    "customerId": 74038,
    "firstName": "test",
    "lastName": "user",
    "addressLine1": "1638 Steve Irwin Way",
    "addressLine2": " Beerwah",
    "city": "Beerwah",
    "state": 80,
    "postcode": 4519,
    "country": 6,
    "phone1": "917228040585",
    "email": "usernewtest425@yopmail.com",
    "isSource": "10",
    "isVerified": true,
    "company": null,
    "isactive": true,
    "storeCode": 8,
    "stateName": "Queensland",
    "countryName": "Australia"
}